# Project 2
Analyzing data from csv datasets found on the web using Pandas

For this project I am going to analyze three different datasets using Pandas.  

The first dataset is an Airbnb dataset found at, first I'll load up the dataset into a pandas dataframe

In [43]:
import pandas as pd
import numpy as np

airbnb_data=pd.read_csv('airbnb_listings.csv')
airbnb_data

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2454,superCondo,2688,Ben,Manhattan,Midtown,40.755523,-73.967679,Entire home/apt,137,7,1,2019-01-30,1.00,1,65
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.647486,-73.972370,Private room,149,1,9,2018-10-19,0.23,8,365
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.753621,-73.983774,Entire home/apt,225,1,43,2019-01-02,0.38,2,365
3,3330,++ Brooklyn Penthouse Guestroom ++,4177,Jbee,Brooklyn,Williamsburg,40.708558,-73.942362,Private room,70,5,39,2018-12-07,0.35,3,290
4,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.809018,-73.941902,Private room,150,3,0,NaN,NaN,1,365
5,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.685138,-73.959757,Entire home/apt,89,1,231,2019-01-17,4.37,1,162
6,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.798514,-73.943991,Entire home/apt,80,10,9,2018-11-19,0.11,1,48
7,5099,Large Cozy 1 BR Apartment In Midtown East,7322,Chris,Manhattan,Murray Hill,40.747672,-73.974997,Entire home/apt,185,2,70,2018-12-02,0.59,1,0
8,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.686882,-73.955957,Private room,60,45,49,2017-10-05,0.42,1,0
9,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.764887,-73.984930,Private room,79,2,410,2019-01-14,3.46,1,150
10,5203,Cozy Clean Guest Room - Family Apt,7490,MaryEllen,Manhattan,Upper West Side,40.801779,-73.967229,Private room,79,2,118,2017-07-21,1.03,1,0
11,5216,Super Large APT,7510,Tonya,Manhattan,Flatiron District,40.743572,-73.989987,Entire home/apt,126,26,35,2018-12-31,0.29,5,337
12,5238,Cute & Cozy Lower East Side 1 bdrm,7549,Ben,Manhattan,Chinatown,40.713444,-73.990375,Entire home/apt,150,1,153,2019-01-04,1.33,4,262
13,5295,Beautiful 1br on Upper West Side,7702,Lena,Manhattan,Upper West Side,40.803158,-73.965446,Entire home/apt,135,5,43,2018-10-31,0.36,1,53
14,5441,Central Manhattan/near Broadway,7989,Kate,Manhattan,Hell's Kitchen,40.760760,-73.988667,Private room,85,2,170,2019-01-01,1.41,1,0
15,5586,Rooftop Deck/City Views. Great Apt,8526,Susan,Manhattan,Upper East Side,40.761198,-73.960633,Entire home/apt,175,3,38,2018-12-31,0.32,1,41
16,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.668290,-73.987791,Private room,89,4,162,2018-11-17,1.36,3,336
17,6021,Wonderful Guest Bedroom in Manhattan for SINGLES,11528,Claudio,Manhattan,Upper West Side,40.798264,-73.961134,Private room,85,2,100,2018-12-18,0.84,1,365
18,6090,West Village Nest - Superhost,11975,Alina,Manhattan,West Village,40.735305,-74.005247,Entire home/apt,175,100,27,2018-10-31,0.23,1,108
19,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.708372,-73.953519,Entire home/apt,140,2,122,2019-01-28,1.03,1,92
20,6990,UES Beautiful Blue Room / Oak Room,16800,Cyn,Manhattan,East Harlem,40.789624,-73.948020,Private room,75,30,229,2018-09-15,2.03,2,315
21,7036,Large Guest Room for Broolyn Condo,53179,Ed And Kiko,Brooklyn,Kensington,40.645223,-73.982930,Private room,65,3,4,2011-09-20,0.04,3,365
22,7097,Perfect for Your Parents + Garden,17571,Jane,Brooklyn,Fort Greene,40.691685,-73.971845,Entire home/apt,215,2,179,2019-01-19,1.62,1,330
23,7322,Chelsea Perfect,18946,Doti,Manhattan,Chelsea,40.746873,-74.005952,Private room,140,1,246,2018-09-09,2.10,1,0
24,7726,Hip Historic Brownstone Apartment with Backyard,20950,Adam And Charity,Brooklyn,Crown Heights,40.675919,-73.946939,Entire home/apt,99,3,31,2019-01-12,4.63,1,76
25,7801,Sweet and Spacious Brooklyn Loft,21207,Chaya,Brooklyn,Williamsburg,40.718418,-73.957183,Entire home/apt,299,3,9,2011-12-28,0.08,1,0
26,7970,Chic Chelsea,10496,Cee,Manhattan,Flatiron District,40.743003,-73.990652,Entire home/apt,120,35,38,2018-09-20,0.33,1,254
27,8024,CBG CtyBGd HelpsHaiti rm#1:1-4,22486,Lisel,Brooklyn,Park Slope,40.680694,-73.977058,Private room,130,2,124,2019-01-02,1.09,4,365
28,8110,CBG Helps Haiti Rm #2,22486,Lisel,Brooklyn,Park Slope,40.680006,-73.978645,Private room,100,2,64,2018-12-11,0.58,4,365
29,8343,"Quiet, Spacious 3BR, 1.5 BA EV apt w/yard",24222,Lori,Manhattan,East Village,40.724838,-73.980588,Entire home/apt,211,3,16,2019-01-18,0.18,3,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50198,32045241,Beautiful 3Bedroom Apt in the Upper East Side!!,38082447,Shir,Manhattan,Upper East Side,40.769713,-73.954836,Entire home/apt,90,27,0,NaN,NaN,2,52
50199,32045303,Lux one bedroom available in trendy Nolita!,236839319,Kelli,Manhattan,Little Italy,40.717901,-73.998557,Private room,56,30,0,NaN,NaN,3,349
50200,32045403,Comfortable Private Room in Crown Heights,64213111,Meir,Brooklyn,Prospect-Lefferts Gardens,40.660880,-73.943625,Private room,50,2,0,NaN,NaN,1,7
50201,32045441,Beautiful 3 bed 1 bath in Iconic Bed-Stuy,1405865,Taylor,Brooklyn,Bedford-Stuyvesant,40.688007,-73.944614,Entire home/apt,61,15,0,NaN,NaN,1,20
50202,32045763,Home away by the beach,234781729,Oluwatosin,Queens,Edgemere,40.592642,-73.773211,Private room,50,1,0,NaN,NaN,2,179
50203,32046149,Cozy home by the beach,234781729,Oluwatosin,Queens,Edgemere,40.594534,-73.773744,Private room,35,1,0,NaN,NaN,2,179
50204,32047002,3 JFK Layover - Express train to Manhattan-30 ...,67746251,Gasminee,Queens,Ozone Park,40.682404,-73.849971,Private room,35,1,0,NaN,NaN,3,90
50205,32047800,Cozy Room starting at $67 a night,9898029,Anthony,Brooklyn,East Flatbush,40.649976,-73.923576,Private room,67,3,0,NaN,NaN,5,357
50206,32047965,"Private bdrm, living room, bathroom, kitchenette",240283485,Liz,Manhattan,East Village,40.726666,-73.987631,Private room,150,2,0,NaN,NaN,1,365
50207,32048480,"Calm, Quiet Space in Bedstuy",60403058,Maria,Brooklyn,Bedford-Stuyvesant,40.687354,-73.931176,Private room,60,2,0,NaN,NaN,1,22
50208,32048560,Cosy one bedroom apartment in Hells Kitchen,240289379,Laure,Manhattan,Hell's Kitchen,40.763635,-73.995064,Entire home/apt,120,4,0,NaN,NaN,1,31
50209,32048862,Brooklyn's Cutest Twin Beds W/Spa Amenities,89985620,Annette C,Brooklyn,Flatlands,40.622971,-73.929707,Private room,42,2,0,NaN,NaN,3,357
50210,32048883,Bayridge Brooklyn Beauty Townhouse!,240291101,Camille,Brooklyn,Bay Ridge,40.631205,-74.022418,Entire home/apt,150,4,0,NaN,NaN,1,363
50211,32048953,Charming Meatpacking Loft,5083078,Leia,Manhattan,Chelsea,40.741067,-74.003356,Private room,195,1,0,NaN,NaN,2,215
50212,32050059,Comfortable & Simple Room,592967,Portia,Brooklyn,Crown Heights,40.677981,-73.942301,Private room,66,7,0,NaN,NaN,1,83
50213,32050071,Modern luxury apartment in the heart of Noho,6073347,Elisabeth,Manhattan,NoHo,40.727030,-73.992643,Entire home/apt,189,5,0,NaN,NaN,1,3
50214,32050188,Private room in the heart of Manhattan NYC,239519185,Raphael,Manhattan,Hell's Kitchen,40.761243,-73.989399,Private room,120,1,0,NaN,NaN,2,364
50215,32050215,Stylish Apartment in Soho/Chinatown,500083,Mi,Manhattan,Chinatown,40.716717,-73.997995,Entire home/apt,170,1,0,NaN,NaN,2,89
50216,32050230,法拉盛皇后大学温馨房间,202697970,Joyce,Queens,Flushing,40.737731,-73.809552,Private room,45,1,0,NaN,NaN,1,173
50217,32050625,CHEAP APT @Brooklyn NYC,216061468,Rashmi,Brooklyn,Flatbush,40.651471,-73.964757,Entire home/apt,78,1,0,NaN,NaN,1,29
50218,32050937,Xanadu,21416718,Andrew,Brooklyn,Williamsburg,40.716061,-73.962685,Entire home/apt,300,2,0,NaN,NaN,1,82
50219,32050983,Hudson River/GW Bridge \nview. Spacious room,240311383,Ana,Manhattan,Washington Heights,40.847249,-73.942739,Private room,85,2,0,NaN,NaN,1,159
50220,32053614,Tiny Room in Manhattan only 1 person,77304447,Genesis,Manhattan,Harlem,40.820652,-73.954831,Private room,35,4,0,NaN,NaN,4,100
50221,32055241,BIG BIG LOFT STYLE STUDIO IN WEST VILLAGE,14563616,Anna/Phillip,Manhattan,West Village,40.734583,-74.007024,Entire home/apt,300,1,0,NaN,NaN,2,272
50222,32055773,Fully furnished room with en-suite bath,53735410,Juliann,Brooklyn,Bedford-Stuyvesant,40.692321,-73.935382,Private room,39,5,0,NaN,NaN,1,282
50223,32056234,STEPS FROM EAST RIVER-DOORMAN/GYM/LAUNDRY,200380610,Pranjal,Manhattan,Midtown,40.756714,-73.964475,Entire home/apt,220,30,0,NaN,NaN,71,364
50224,32057587,STUNNING 1BR-DOORMAN/GYM/LAUNDRY,200380610,Pranjal,Manhattan,Midtown,40.747594,-73.987517,Entire home/apt,235,30,0,NaN,NaN,71,365
50225,32058485,Williamsburg Home,231443122,Francisco,Brooklyn,Williamsburg,40.717753,-73.959266,Entire home/apt,150,30,0,NaN,NaN,3,365
50226,32058709,Sutton place luxury apartment with a view!,23637375,Param,Manhattan,Midtown,40.758912,-73.962273,Entire home/apt,450,1,0,NaN,NaN,1,56
50227,32058864,LUXURY IN MIDTOWN EAST-DOORMAN/GYM/LAUNDRY,200380610,Pranjal,Manhattan,Murray Hill,40.743954,-73.971704,Entire home/apt,285,30,0,NaN,NaN,71,365

# First question - what is the average price of a private room in Manhattan?
Let's dig into the pandas dataframe to find apartments in Manhattan, then, Private rooms, and finally run an average of the price

In [5]:
ma_data = airbnb_data[airbnb_data['neighbourhood_group'].str.contains("Manhattan")]
ma_pr_data = ma_data[ma_data['room_type'].str.contains("Private room")]
ma_pr_data

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
4,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.809018,-73.941902,Private room,150,3,0,NaN,NaN,1,365
9,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.764887,-73.984930,Private room,79,2,410,2019-01-14,3.46,1,150
10,5203,Cozy Clean Guest Room - Family Apt,7490,MaryEllen,Manhattan,Upper West Side,40.801779,-73.967229,Private room,79,2,118,2017-07-21,1.03,1,0
14,5441,Central Manhattan/near Broadway,7989,Kate,Manhattan,Hell's Kitchen,40.760760,-73.988667,Private room,85,2,170,2019-01-01,1.41,1,0
17,6021,Wonderful Guest Bedroom in Manhattan for SINGLES,11528,Claudio,Manhattan,Upper West Side,40.798264,-73.961134,Private room,85,2,100,2018-12-18,0.84,1,365
20,6990,UES Beautiful Blue Room / Oak Room,16800,Cyn,Manhattan,East Harlem,40.789624,-73.948020,Private room,75,30,229,2018-09-15,2.03,2,315
23,7322,Chelsea Perfect,18946,Doti,Manhattan,Chelsea,40.746873,-74.005952,Private room,140,1,246,2018-09-09,2.10,1,0
32,8700,Magnifique Suite au N de Manhattan - vue Cloitres,26394,Claude & Sophie,Manhattan,Inwood,40.867543,-73.926387,Private room,80,4,0,NaN,NaN,1,0
34,9518,"SPACIOUS, LOVELY FURNISHED MANHATTAN BEDROOM",31374,Shon,Manhattan,Inwood,40.864817,-73.921055,Private room,44,3,106,2018-12-10,1.15,2,344
36,9668,front room/double bed,32294,Ssameer A.K.A. Trip,Manhattan,Harlem,40.822452,-73.951036,Private room,50,3,230,2018-12-02,2.02,3,348
37,9704,Spacious 1 bedroom in luxe building,32045,Teri,Manhattan,Harlem,40.813053,-73.954662,Private room,52,2,80,2018-11-11,1.41,1,365
39,9783,back room/bunk beds,32294,Ssameer A.K.A. Trip,Manhattan,Harlem,40.821302,-73.953183,Private room,50,3,259,2019-01-01,2.35,3,355
46,12192,ENJOY Downtown NYC!,46978,Edward,Manhattan,East Village,40.722901,-73.981990,Private room,68,2,237,2018-12-23,2.10,2,26
49,12318,West Side Retreat,16800,Cyn,Manhattan,Upper West Side,40.790094,-73.979269,Private room,135,4,76,2019-01-04,0.68,2,196
63,14468,Under the Empire State Building/Midtown Manhattan,56909,Peter,Manhattan,Kips Bay,40.743542,-73.981222,Private room,85,3,15,2019-01-04,0.84,2,304
66,14991,"Great Location, Manhattan Bedroom!",59023,Bianca,Manhattan,Lower East Side,40.720035,-73.991041,Private room,100,5,18,2018-10-25,0.17,1,365
67,15220,Best Location in NYC! TIMES SQUARE!,59734,Luiz,Manhattan,Hell's Kitchen,40.755310,-73.992929,Private room,69,3,273,2019-01-15,2.47,2,303
79,16421,Your Heaven in Hells Kitchen,63924,Mark,Manhattan,Hell's Kitchen,40.759786,-73.991193,Private room,52,30,189,2018-10-31,1.71,1,298
81,16580,"Sunny, Modern room in East Village!",64442,Reka,Manhattan,East Village,40.726488,-73.979035,Private room,80,1,303,2019-02-01,4.57,2,92
83,16821,Large Room in Amazing East Village Apt,4396,Casey,Manhattan,East Village,40.722982,-73.984736,Private room,79,1,97,2019-01-04,1.23,2,364
86,17092,Cool Room in Hell's Kitchen,66243,Enzo,Manhattan,Hell's Kitchen,40.763419,-73.988654,Private room,51,20,19,2019-01-13,0.40,1,230
91,17693,"HARLEM, NEW YORK WELCOMES YOU!!",68428,Tye And Etienne,Manhattan,Washington Heights,40.831386,-73.940954,Private room,65,2,39,2019-01-03,1.54,2,365
94,18152,Manhattan Room,69942,Victoria,Manhattan,Upper East Side,40.768648,-73.950582,Private room,200,1,123,2019-01-09,1.37,1,345
98,18728,Beautiful Meatpacking District Loft,71876,DAVID And RICK,Manhattan,Chelsea,40.741379,-74.001967,Private room,150,3,159,2019-01-18,1.65,1,273
104,19319,Private room Long Term Rental,44263,Ana,Manhattan,Lower East Side,40.711402,-73.987935,Private room,92,30,93,2018-12-13,0.87,1,287
107,20299,Oh glorious spring!,62407,Edward,Manhattan,East Village,40.723342,-73.984403,Private room,55,3,180,2018-12-22,1.68,1,72
108,20300,Great Location for NYC,76627,Pas,Manhattan,East Village,40.729120,-73.980571,Private room,50,1,2,2016-02-14,0.05,1,0
120,21644,"Upper Manhattan, New York",82685,Elliott,Manhattan,Harlem,40.828028,-73.947308,Private room,89,1,1,2018-10-09,0.26,1,365
121,21794,COZY QUIET room 4 DOOGLERS!,83257,Olan,Manhattan,Chelsea,40.740085,-74.002706,Private room,99,6,28,2019-01-01,0.26,2,363
123,22918,loft bed - near transportation-15min to times sq,32294,Ssameer A.K.A. Trip,Manhattan,Harlem,40.822785,-73.951387,Private room,60,3,11,2019-01-03,1.48,3,63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50097,32005497,NEW! Amazing room in 3 BR flat w/ rooftop in SOHO,17236151,Matthias,Manhattan,Nolita,40.724342,-73.994307,Private room,200,4,0,NaN,NaN,1,11
50101,32008158,Cozy dreamy located private getaway,94173816,Priel,Manhattan,Upper East Side,40.762310,-73.964672,Private room,82,1,0,NaN,NaN,1,25
50108,32009894,Room 3 in Furnished Apartment- Beautiful 3 Bed...,239355304,Adi,Manhattan,Nolita,40.721760,-73.996238,Private room,69,30,0,NaN,NaN,8,62
50128,32015007,Cozy room next to subway!,240033083,Patrik,Manhattan,Harlem,40.822721,-73.954784,Private room,70,2,0,NaN,NaN,1,61
50134,32016041,Spectacular Chinatown Apartment,14249909,Evan,Manhattan,Little Italy,40.718977,-73.997628,Private room,95,2,0,NaN,NaN,2,8
50135,32016160,Room in Fully Furnished - Spacious 3 Bedroom Apt,239355304,Adi,Manhattan,Nolita,40.720317,-73.995396,Private room,56,30,0,NaN,NaN,8,69
50136,32016609,Time square/ Hell’s Kitchen,98091426,Leah,Manhattan,Theater District,40.762078,-73.985354,Private room,55,3,1,2019-02-01,1.00,1,21
50138,32016869,1 Bed/shared bath in the heart of Nolita! (Soho),24077660,Benedetta,Manhattan,Nolita,40.722548,-73.994080,Private room,70,6,0,NaN,NaN,2,48
50146,32020853,"★ Clean, Private BR in Little Italy/Chinatown ★",14249909,Evan,Manhattan,Chinatown,40.718248,-73.996506,Private room,99,3,0,NaN,NaN,2,7
50149,32021345,Beautiful Room Amazing View w/Balcony 150 reviews,110020623,Emily,Manhattan,Flatiron District,40.741334,-73.989292,Private room,100,1,0,NaN,NaN,4,240
50150,32021582,Private BIG BEDROOM with own BATHROOM 150(Revi...,110020623,Emily,Manhattan,Flatiron District,40.741033,-73.988360,Private room,100,1,0,NaN,NaN,4,251
50151,32022587,Peaceful modern room in SoHo,1475812,Ignani,Manhattan,Nolita,40.722615,-73.995332,Private room,140,2,0,NaN,NaN,2,216
50155,32023208,Comfortable home,233557783,Xiangrui,Manhattan,Washington Heights,40.832785,-73.941113,Private room,60,1,0,NaN,NaN,1,357
50156,32023903,Luxury Master Bedroom at Korea Town/Empire St ...,240108110,Melissa,Manhattan,Midtown,40.747417,-73.987483,Private room,189,5,0,NaN,NaN,1,17
50157,32025639,Enjoy the View in a Cozy Lux Condo,56656728,Bret,Manhattan,Greenwich Village,40.725546,-73.996936,Private room,79,1,0,NaN,NaN,5,23
50158,32026654,AMAZING PRIVATE BEDROOM BEST LOCATION 150 REV...,110020623,Emily,Manhattan,Flatiron District,40.742070,-73.989212,Private room,87,1,0,NaN,NaN,4,252
50165,32036822,Private comfy and large room in Washington Hei...,36323224,Valentina,Manhattan,Washington Heights,40.846687,-73.940277,Private room,40,1,0,NaN,NaN,1,86
50166,32036850,Charming lower east side room,165863135,Amanda,Manhattan,Lower East Side,40.720262,-73.987865,Private room,80,27,0,NaN,NaN,1,153
50167,32036997,Private room in spacious uptown NYC apartment,240194042,Sarita,Manhattan,Harlem,40.823503,-73.953913,Private room,30,21,0,NaN,NaN,1,1
50168,32037066,Cozy BR in the heart of Chelsea with Outdoor S...,40300276,Bryan,Manhattan,Chelsea,40.744294,-73.992947,Private room,175,2,0,NaN,NaN,1,30
50173,32039206,Large East Harlem room,26390107,Caitlin,Manhattan,East Harlem,40.794032,-73.936531,Private room,70,2,0,NaN,NaN,1,14
50184,32041621,Ben's extra bedroom,62589092,Chen,Manhattan,Harlem,40.809958,-73.941909,Private room,53,1,0,NaN,NaN,1,83
50186,32042141,Distinctive Private Suite on Central Park South,44958,Dan,Manhattan,Midtown,40.766229,-73.980472,Private room,200,7,0,NaN,NaN,1,28
50189,32042820,Harlem Sweets 2,187419882,Terrence,Manhattan,Harlem,40.828845,-73.941203,Private room,62,2,0,NaN,NaN,3,88
50199,32045303,Lux one bedroom available in trendy Nolita!,236839319,Kelli,Manhattan,Little Italy,40.717901,-73.998557,Private room,56,30,0,NaN,NaN,3,349
50206,32047965,"Private bdrm, living room, bathroom, kitchenette",240283485,Liz,Manhattan,East Village,40.726666,-73.987631,Private room,150,2,0,NaN,NaN,1,365
50211,32048953,Charming Meatpacking Loft,5083078,Leia,Manhattan,Chelsea,40.741067,-74.003356,Private room,195,1,0,NaN,NaN,2,215
50214,32050188,Private room in the heart of Manhattan NYC,239519185,Raphael,Manhattan,Hell's Kitchen,40.761243,-73.989399,Private room,120,1,0,NaN,NaN,2,364
50219,32050983,Hudson River/GW Bridge \nview. Spacious room,240311383,Ana,Manhattan,Washington Heights,40.847249,-73.942739,Private room,85,2,0,NaN,NaN,1,159
50220,32053614,Tiny Room in Manhattan only 1 person,77304447,Genesis,Manhattan,Harlem,40.820652,-73.954831,Private room,35,4,0,NaN,NaN,4,100

In [6]:
ma_pr_data["price"].mean()

112.52065096782148

# The average price of a private room in Manhattan on airbnb is 113 a night

The second dataset is a set of rent data I found on streeteasy.net.

In [8]:
rent_data = pd.read_csv('medianAskingRent_All.csv')
rent_data

,areaName,Borough,areaType,2010-01,2010-02,2010-03,2010-04,2010-05,2010-06,2010-07,...,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02
0,All Downtown,Manhattan,submarket,3200.0,3200.0,3025.0,3100.0,3100.0,3200.0,3195.0,...,3825.0,3800.0,3795.0,3800.0,3805.0,3800.0,3872.0,3800.0,3820.0,3895.0
1,All Midtown,Manhattan,submarket,2895.0,2800.0,2800.0,2850.0,2900.0,2950.0,3000.0,...,3500.0,3500.0,3500.0,3500.0,3511.0,3550.0,3527.0,3573.0,3500.0,3595.0
2,All Upper East Side,Manhattan,submarket,2469.0,2450.0,2400.0,2500.0,2550.0,2550.0,2595.0,...,2850.0,2900.0,2925.0,2900.0,2895.0,2995.0,2995.0,3000.0,3000.0,3000.0
3,All Upper Manhattan,Manhattan,submarket,1825.0,1800.0,1795.0,1800.0,1823.0,1850.0,1875.0,...,2395.0,2400.0,2430.0,2400.0,2350.0,2350.0,2300.0,2300.0,2300.0,2336.0
4,All Upper West Side,Manhattan,submarket,2895.0,2800.0,2750.0,2800.0,2798.0,2795.0,2800.0,...,3300.0,3350.0,3322.0,3310.0,3400.0,3395.0,3395.0,3400.0,3400.0,3360.0
5,Alley Park,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Astoria,Queens,neighborhood,1600.0,1650.0,1620.0,1600.0,1700.0,1700.0,1600.0,...,2200.0,2200.0,2223.0,2250.0,2250.0,2200.0,2150.0,2150.0,2195.0,2199.0
7,Auburndale,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1850.0,2098.0,2095.0,2000.0,1895.0,1995.0,1995.0,1900.0,2045.0,2045.0
8,Bath Beach,Brooklyn,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2000.0,1850.0,1700.0,1675.0,1675.0,1750.0,1725.0,1675.0,1700.0,1563.0
9,Battery Park City,Manhattan,neighborhood,3495.0,3346.0,3268.0,3295.0,3100.0,3395.0,3200.0,...,4650.0,4525.0,4750.0,4854.0,4995.0,4874.0,4500.0,4310.0,4355.0,4500.0
10,Bay Ridge,Brooklyn,neighborhood,1350.0,1388.0,1350.0,1350.0,1350.0,1350.0,1300.0,...,1950.0,1950.0,1850.0,1997.0,2025.0,2000.0,1995.0,1900.0,1900.0,1999.0
11,Baychester,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Bayside,Queens,neighborhood,1775.0,1838.0,1888.0,1838.0,NaN,NaN,NaN,...,2300.0,2375.0,2400.0,2475.0,2350.0,2500.0,2350.0,2100.0,2150.0,2275.0
13,Bedford Park,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1490.0,1550.0,1575.0,1550.0,1438.0,1823.0,1600.0,NaN,1875.0,1790.0
14,Bedford-Stuyvesant,Brooklyn,neighborhood,1650.0,1650.0,1600.0,1650.0,1650.0,1593.0,1460.0,...,2500.0,2500.0,2575.0,2595.0,2550.0,2500.0,2475.0,2475.0,2429.0,2450.0
15,Bellerose,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Belmont,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1875.0,2000.0,1879.0,1840.0,2100.0,2100.0,1813.0,1700.0,1998.0,2200.0
17,Bensonhurst,Brooklyn,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1880.0,1879.0,1700.0,1850.0,1900.0,1850.0,1875.0,1900.0,1850.0,1850.0
18,Bergen Beach,Brooklyn,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2175.0,2275.0,2300.0,2150.0,2225.0,2063.0,2325.0,2300.0,2225.0,2100.0
19,Boerum Hill,Brooklyn,neighborhood,2600.0,2700.0,2600.0,2500.0,2500.0,2463.0,2475.0,...,3400.0,3257.0,3225.0,3200.0,3199.0,3250.0,3500.0,3100.0,3000.0,2950.0
20,Borough Park,Brooklyn,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1750.0,1850.0,1885.0,1825.0,1800.0,1900.0,1875.0,1700.0,1863.0,1925.0
21,Bowne Park,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Briarwood,Queens,neighborhood,NaN,1325.0,NaN,NaN,NaN,NaN,NaN,...,1720.0,1749.0,1750.0,1699.0,1750.0,1750.0,1750.0,1815.0,1763.0,1700.0
23,Brighton Beach,Brooklyn,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2075.0,2125.0,2113.0,2099.0,2100.0,2050.0,2000.0,2100.0,2200.0,2190.0
24,Bronx,Bronx,borough,1600.0,1600.0,1508.0,1508.0,1600.0,1500.0,1529.0,...,1900.0,1900.0,1895.0,1877.0,1900.0,1900.0,1825.0,1850.0,1900.0,1875.0
25,Bronxwood,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1750.0,1550.0,1595.0,1588.0,1550.0,1610.0,1595.0,1700.0,1650.0,1598.0
26,Brooklyn,Brooklyn,borough,2200.0,2150.0,2150.0,2150.0,2200.0,2250.0,2300.0,...,2590.0,2600.0,2695.0,2680.0,2600.0,2550.0,2500.0,2500.0,2500.0,2500.0
27,Brooklyn Heights,Brooklyn,neighborhood,2350.0,2300.0,2400.0,2200.0,2400.0,2250.0,2600.0,...,2979.0,3100.0,3191.0,3250.0,3425.0,3300.0,3200.0,3250.0,3125.0,3200.0
28,Brookville,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Brownsville,Brooklyn,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1795.0,1800.0,1850.0,1850.0,1875.0,1950.0,1900.0,1900.0,2100.0,2100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,South Queens,Queens,submarket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1850.0,1973.0,2000.0,2050.0,2000.0,1995.0,1938.0,1850.0,1988.0,1884.0
173,South Richmond Hill,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,Springfield Gardens,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,St. Albans,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,Staten Island,Staten Island,borough,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1829.0,1887.0,1950.0,2000.0,2000.0,1900.0,1970.0,1890.0,1865.0,1872.0
177,Stuyvesant Town/PCV,Manhattan,neighborhood,NaN,NaN,NaN,NaN,NaN,2903.0,NaN,...,3818.0,3807.0,3822.0,3966.0,3769.0,4052.0,3741.0,3774.0,4147.0,3689.0
178,Sunnyside,Queens,neighborhood,1550.0,1475.0,1500.0,1550.0,1450.0,1400.0,1400.0,...,2000.0,2000.0,2000.0,2000.0,2000.0,1925.0,1954.0,1963.0,1950.0,1950.0
179,Sunset Park,Brooklyn,neighborhood,1500.0,1500.0,1400.0,1400.0,1425.0,1450.0,1400.0,...,2154.0,2200.0,2200.0,2000.0,2000.0,1995.0,2000.0,1950.0,1985.0,1900.0
180,The Rockaways,Queens,submarket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2100.0,1963.0,2100.0,1900.0,1890.0,1900.0,2020.0,1997.0,1890.0,1900.0
181,Throgs Neck,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2499.0,2400.0,2400.0,2200.0,2150.0,2150.0,2150.0,1600.0,NaN
182,Tremont,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1800.0,1825.0,1538.0,1849.0,1950.0,1800.0,1750.0,1700.0,1600.0,1800.0
183,Tribeca,Manhattan,neighborhood,6500.0,6773.0,6500.0,6400.0,6500.0,6500.0,6000.0,...,6408.0,6800.0,6750.0,7000.0,7243.0,6860.0,6900.0,6694.0,6579.0,5985.0
184,University Heights,Bronx,neighborhood,1100.0,1100.0,NaN,NaN,NaN,NaN,NaN,...,1698.0,1750.0,1875.0,1750.0,1697.0,1691.0,1649.0,1645.0,1599.0,1750.0
185,Upper East Side,Manhattan,neighborhood,2469.0,2450.0,2400.0,2500.0,2550.0,2550.0,2595.0,...,2850.0,2900.0,2925.0,2900.0,2895.0,2995.0,2995.0,3000.0,3000.0,3000.0
186,Upper West Side,Manhattan,neighborhood,2895.0,2800.0,2750.0,2800.0,2798.0,2795.0,2800.0,...,3300.0,3350.0,3322.0,3310.0,3400.0,3395.0,3395.0,3400.0,3400.0,3360.0
187,Utopia,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,Van Nest,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1400.0,1575.0,NaN,NaN
189,Wakefield,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1450.0,1900.0,1900.0,1600.0,2050.0,2100.0,NaN,1700.0,2200.0,2200.0
190,Washington Heights,Manhattan,neighborhood,1550.0,1545.0,1597.0,1600.0,1650.0,1653.0,1678.0,...,2154.0,2200.0,2250.0,2250.0,2200.0,2248.0,2222.0,2195.0,2150.0,2200.0
191,West Harlem,Manhattan,neighborhood,1795.0,NaN,NaN,NaN,1675.0,NaN,NaN,...,2650.0,2650.0,2650.0,2963.0,2418.0,2500.0,2495.0,2450.0,2450.0,2450.0
192,West Village,Manhattan,neighborhood,3265.0,3395.0,3113.0,3250.0,3073.0,3138.0,3195.0,...,3853.0,3850.0,3850.0,3950.0,3900.0,3873.0,3950.0,3900.0,3900.0,3809.0
193,Westchester Village,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,Whitestone,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2200.0,2150.0,2200.0,NaN,NaN,2250.0,2100.0,2338.0,2375.0,2300.0
195,Williamsbridge,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1663.0,1675.0,1763.0,NaN,NaN,2150.0,2125.0,2150.0,1750.0,2125.0
196,Williamsburg,Brooklyn,neighborhood,2500.0,2500.0,2500.0,2600.0,2625.0,2700.0,2775.0,...,3000.0,3000.0,3000.0,3025.0,3000.0,3000.0,2900.0,2895.0,2997.0,3033.0
197,Windsor Terrace,Brooklyn,neighborhood,1600.0,1650.0,1650.0,1600.0,1800.0,1825.0,1995.0,...,2500.0,2500.0,2550.0,2641.0,2650.0,2600.0,2700.0,2580.0,2600.0,2795.0
198,Woodhaven,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1625.0,1763.0,1950.0,1850.0,1725.0,1850.0,1923.0,1742.0,1750.0,1950.0
199,Woodlawn,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,Woodside,Queens,neighborhood,1813.0,NaN,1398.0,2000.0,1475.0,1488.0,NaN,...,1995.0,1985.0,1750.0,1825.0,2000.0,1850.0,1948.0,1890.0,1875.0,1850.0
201,Woodstock,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2240.0,2155.0,1650.0,1781.0,2300.0,1950.0,1950.0,1789.0,2199.0,1900.0

# Second question - what area in Manhattan had the lowest average price between 2010 and 2018?

In [15]:
ma_rent_data = rent_data[rent_data['Borough'].str.contains('Manhattan', na=False)]
ma_rent_data

,areaName,Borough,areaType,2010-01,2010-02,2010-03,2010-04,2010-05,2010-06,2010-07,...,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02
0,All Downtown,Manhattan,submarket,3200.0,3200.0,3025.0,3100.0,3100.0,3200.0,3195.0,...,3825.0,3800.0,3795.0,3800.0,3805.0,3800.0,3872.0,3800.0,3820.0,3895.0
1,All Midtown,Manhattan,submarket,2895.0,2800.0,2800.0,2850.0,2900.0,2950.0,3000.0,...,3500.0,3500.0,3500.0,3500.0,3511.0,3550.0,3527.0,3573.0,3500.0,3595.0
2,All Upper East Side,Manhattan,submarket,2469.0,2450.0,2400.0,2500.0,2550.0,2550.0,2595.0,...,2850.0,2900.0,2925.0,2900.0,2895.0,2995.0,2995.0,3000.0,3000.0,3000.0
3,All Upper Manhattan,Manhattan,submarket,1825.0,1800.0,1795.0,1800.0,1823.0,1850.0,1875.0,...,2395.0,2400.0,2430.0,2400.0,2350.0,2350.0,2300.0,2300.0,2300.0,2336.0
4,All Upper West Side,Manhattan,submarket,2895.0,2800.0,2750.0,2800.0,2798.0,2795.0,2800.0,...,3300.0,3350.0,3322.0,3310.0,3400.0,3395.0,3395.0,3400.0,3400.0,3360.0
9,Battery Park City,Manhattan,neighborhood,3495.0,3346.0,3268.0,3295.0,3100.0,3395.0,3200.0,...,4650.0,4525.0,4750.0,4854.0,4995.0,4874.0,4500.0,4310.0,4355.0,4500.0
35,Central Harlem,Manhattan,neighborhood,1950.0,1950.0,1893.0,1863.0,1900.0,1900.0,1850.0,...,2500.0,2500.0,2550.0,2600.0,2499.0,2450.0,2400.0,2400.0,2437.0,2438.0
36,Central Park South,Manhattan,neighborhood,6000.0,6000.0,5950.0,6500.0,6200.0,5800.0,5575.0,...,6800.0,6850.0,7500.0,7325.0,7950.0,7800.0,8999.0,7725.0,7100.0,7475.0
38,Chelsea,Manhattan,neighborhood,3200.0,3400.0,3245.0,3200.0,3200.0,3395.0,3400.0,...,3995.0,4003.0,3998.0,4100.0,4150.0,4036.0,4000.0,4064.0,4050.0,4295.0
39,Chinatown,Manhattan,neighborhood,2900.0,2900.0,2550.0,2200.0,2200.0,2248.0,2500.0,...,2925.0,2850.0,2700.0,2800.0,2795.0,2500.0,2700.0,2799.0,2700.0,2800.0
41,Civic Center,Manhattan,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,East Harlem,Manhattan,neighborhood,1895.0,1900.0,1895.0,1975.0,1998.0,2095.0,2195.0,...,2352.0,2390.0,2387.0,2350.0,2350.0,2314.0,2250.0,2250.0,2295.0,2400.0
65,East Village,Manhattan,neighborhood,2500.0,2500.0,2400.0,2500.0,2595.0,2595.0,2600.0,...,3450.0,3400.0,3325.0,3395.0,3250.0,3200.0,3143.0,3106.0,3100.0,3175.0
69,Financial District,Manhattan,neighborhood,3198.0,3100.0,3015.0,3000.0,3200.0,3244.0,3107.0,...,3600.0,3650.0,3750.0,3800.0,3783.0,3750.0,3720.0,3692.0,3755.0,3820.0
71,Flatiron,Manhattan,neighborhood,3895.0,3750.0,3550.0,3695.0,3893.0,3850.0,3900.0,...,4550.0,4581.0,4600.0,4600.0,4850.0,4821.0,4500.0,4620.0,4750.0,4871.0
83,Gramercy Park,Manhattan,neighborhood,3100.0,3000.0,2995.0,3100.0,2995.0,2950.0,2900.0,...,3625.0,3500.0,3590.0,3500.0,3595.0,3408.0,3575.0,3625.0,3573.0,3800.0
86,Greenwich Village,Manhattan,neighborhood,3200.0,3200.0,2979.0,3000.0,3000.0,3000.0,3000.0,...,3650.0,3800.0,3800.0,3738.0,3838.0,3773.0,3998.0,3950.0,4195.0,3825.0
88,Hamilton Heights,Manhattan,neighborhood,1650.0,1700.0,1688.0,1800.0,1695.0,1750.0,1795.0,...,2475.0,2400.0,2500.0,2500.0,2595.0,2400.0,2487.0,2400.0,2375.0,2400.0
94,Inwood,Manhattan,neighborhood,1400.0,1395.0,1395.0,1395.0,1350.0,1349.0,1363.0,...,1850.0,2000.0,1998.0,1925.0,1925.0,1975.0,1900.0,1875.0,1800.0,1850.0
105,Little Italy,Manhattan,neighborhood,3295.0,3050.0,3000.0,2999.0,2885.0,2600.0,3700.0,...,3087.0,2990.0,3000.0,2773.0,2700.0,3150.0,3173.0,3075.0,3250.0,3098.0
109,Lower East Side,Manhattan,neighborhood,2295.0,2250.0,2295.0,2250.0,2495.0,2400.0,2400.0,...,3250.0,3200.0,3250.0,3300.0,3300.0,3300.0,3300.0,3275.0,3250.0,3250.0
110,Manhattan,Manhattan,borough,2800.0,2795.0,2728.0,2800.0,2800.0,2825.0,2880.0,...,3300.0,3300.0,3300.0,3300.0,3300.0,3275.0,3277.0,3300.0,3295.0,3300.0
112,Manhattanville,Manhattan,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2800.0,2799.0,2795.0,2795.0,2795.0,2375.0,2225.0,2200.0,2150.0,2195.0
113,Marble Hill,Manhattan,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2240.0,2220.0,2013.0,1975.0,2160.0,2425.0,2425.0,2050.0
118,Midtown,Manhattan,neighborhood,3800.0,3900.0,3925.0,4173.0,4000.0,4000.0,3998.0,...,3800.0,3900.0,3850.0,3895.0,3969.0,3995.0,4000.0,3935.0,3900.0,3925.0
119,Midtown East,Manhattan,neighborhood,2695.0,2625.0,2650.0,2700.0,2700.0,2700.0,2800.0,...,3400.0,3400.0,3450.0,3400.0,3395.0,3400.0,3400.0,3450.0,3395.0,3450.0
120,Midtown South,Manhattan,neighborhood,3198.0,3200.0,3250.0,3340.0,3400.0,3375.0,3400.0,...,3684.0,3950.0,3850.0,4045.0,3988.0,3965.0,3850.0,3863.0,3881.0,3980.0
121,Midtown West,Manhattan,neighborhood,2600.0,2650.0,2650.0,2650.0,2790.0,2800.0,3000.0,...,3450.0,3495.0,3463.0,3467.0,3500.0,3500.0,3485.0,3500.0,3470.0,3550.0
124,Morningside Heights,Manhattan,neighborhood,2200.0,2150.0,2100.0,2000.0,2050.0,2178.0,2178.0,...,3150.0,3195.0,3200.0,3225.0,3125.0,3010.0,2966.0,2917.0,2917.0,2844.0
131,Nolita,Manhattan,neighborhood,3248.0,2825.0,3195.0,3273.0,3325.0,3350.0,2900.0,...,3645.0,3695.0,3895.0,3700.0,3595.0,3650.0,3700.0,3500.0,3363.0,3467.0
162,Roosevelt Island,Manhattan,neighborhood,2577.0,2555.0,2404.0,2570.0,2585.0,2500.0,2600.0,...,3210.0,3210.0,3480.0,3660.0,3415.0,3378.0,3277.0,3305.0,3423.0,3200.0
167,Soho,Manhattan,neighborhood,5200.0,5288.0,5275.0,4950.0,4197.0,4000.0,4000.0,...,4995.0,4500.0,4997.0,5500.0,5500.0,5150.0,5500.0,5778.0,6200.0,6700.0
177,Stuyvesant Town/PCV,Manhattan,neighborhood,NaN,NaN,NaN,NaN,NaN,2903.0,NaN,...,3818.0,3807.0,3822.0,3966.0,3769.0,4052.0,3741.0,3774.0,4147.0,3689.0
183,Tribeca,Manhattan,neighborhood,6500.0,6773.0,6500.0,6400.0,6500.0,6500.0,6000.0,...,6408.0,6800.0,6750.0,7000.0,7243.0,6860.0,6900.0,6694.0,6579.0,5985.0
185,Upper East Side,Manhattan,neighborhood,2469.0,2450.0,2400.0,2500.0,2550.0,2550.0,2595.0,...,2850.0,2900.0,2925.0,2900.0,2895.0,2995.0,2995.0,3000.0,3000.0,3000.0
186,Upper West Side,Manhattan,neighborhood,2895.0,2800.0,2750.0,2800.0,2798.0,2795.0,2800.0,...,3300.0,3350.0,3322.0,3310.0,3400.0,3395.0,3395.0,3400.0,3400.0,3360.0
190,Washington Heights,Manhattan,neighborhood,1550.0,1545.0,1597.0,1600.0,1650.0,1653.0,1678.0,...,2154.0,2200.0,2250.0,2250.0,2200.0,2248.0,2222.0,2195.0,2150.0,2200.0
191,West Harlem,Manhattan,neighborhood,1795.0,NaN,NaN,NaN,1675.0,NaN,NaN,...,2650.0,2650.0,2650.0,2963.0,2418.0,2500.0,2495.0,2450.0,2450.0,2450.0
192,West Village,Manhattan,neighborhood,3265.0,3395.0,3113.0,3250.0,3073.0,3138.0,3195.0,...,3853.0,3850.0,3850.0,3950.0,3900.0,3873.0,3950.0,3900.0,3900.0,3809.0

In [19]:
ma_rent_data.loc[ma_rent_data['2010-01'].idxmin()]

areaName          Inwood
Borough        Manhattan
areaType    neighborhood
2010-01             1400
2010-02             1395
2010-03             1395
2010-04             1395
2010-05             1350
2010-06             1349
2010-07             1363
2010-08             1450
2010-09             1595
2010-10             1595
2010-11             1595
2010-12             1600
2011-01             1700
2011-02             1595
2011-03             1573
2011-04             1600
2011-05             1573
2011-06             1395
2011-07             1500
2011-08             1468
2011-09             1600
2011-10             1625
2011-11             1450
2011-12             1510
2012-01             1475
2012-02             1450
2012-03             1465
                ...
2016-09             1800
2016-10             1795
2016-11             1795
2016-12             1795
2017-01             1750
2017-02             1800
2017-03             1850
2017-04             1875
2017-05             1881
2017-06             1850
2017-07             1850
2017-08             1850
2017-09             1845
2017-10             1845
2017-11             1750
2017-12             1795
2018-01             1850
2018-02             1850
2018-03             1900
2018-04             1900
2018-05             1850
2018-06             2000
2018-07             1998
2018-08             1925
2018-09             1925
2018-10             1975
2018-11             1900
2018-12             1875
2019-01             1800
2019-02             1850
Name: 94, Length: 113, dtype: object

# Inwood had the cheapest apartments for rent in Manhattan.

For my final dataset, I chose to examine the SAT scores of all New York High Schools in 2010.

In [40]:
sat_data = pd.read_csv('2010_SAT__College_Board__School_Level_Results.csv')
sat_data

,DBN,School Name,Number of Test Takers,Critical Reading Mean,Mathematics Mean,Writing Mean
0,01M292,Henry Street School for International Studies,31,391,425,385
1,01M448,University Neighborhood High School,60,394,419,387
2,01M450,East Side Community High School,69,418,431,402
3,01M458,SATELLITE ACADEMY FORSYTH ST,26,385,370,378
4,01M509,CMSP HIGH SCHOOL,s,s,s,s
5,01M515,Lower East Side Preparatory High School,154,314,532,314
6,01M539,"New Explorations into Sci, Tech and Math HS",47,568,583,568
7,01M650,CASCADES HIGH SCHOOL,35,411,401,401
8,01M696,BARD HIGH SCHOOL EARLY COLLEGE,138,630,608,630
9,02M047,AMERICAN SIGN LANG ENG DUAL,11,405,415,385
10,02M288,FOOD AND FNANCE HIGH SCHOOL,50,422,412,407
11,02M294,HIGH SCHOOL FOR HIST AND COMM,51,382,364,366
12,02M296,High School of Hospitality Management,43,397,415,391
13,02M298,PACE HIGH SCHOOL,71,424,448,423
14,02M300,Urban Assembly School of Design and Construction,49,405,446,415
15,02M303,The Facing History School,59,381,373,377
16,02M305,Urban Assembly Academy of Government and Law,48,411,406,411
17,02M308,LOWER MANHATTAN ARTS ACADEMY,35,409,381,412
18,02M313,The James Baldwin School,45,421,419,394
19,02M316,Urban Assembly School of Business for Young Wo...,52,401,409,391
20,02M374,GRAMERCY ARTS HIGH SCHOOL,49,395,376,386
21,02M376,NYC iSchool,s,s,s,s
22,02M400,HIGH SCHOOL ENVRNMNTL STUDIES,216,465,480,448
23,02M407,Institute for Collaborative Education,42,484,478,472
24,02M408,Professional Performng Arts School,69,495,465,499
25,02M411,Baruch College Campus High School,96,523,583,528
26,02M412,New York City Laboratory School Collab Studies,108,561,597,567
27,02M413,SCHOOL OF THE FUTURE,79,475,488,466
28,02M414,NEW YORK CITY MUSEUM SCHOOL,90,454,448,435
29,02M416,ELEANOR ROOSEVELT HIGH SCHOOL,122,555,596,567
...,...,...,...,...,...,...
430,30Q555,NEWCOMERS HIGH SCHOOL,147,343,447,346
431,30Q575,ACADEMY OF AMERICAN STUDIES,120,502,505,515
432,30Q580,BACCALAUREATE SCH GLOBAL EDUC,64,560,587,570
433,31R064,Gaynor McCown Expeditionary Learning School,s,s,s,s
434,31R080,MICHAEL J PETRIDES SCHOOL,86,508,523,502
435,31R440,NEW DORP HIGH SCHOOL,282,431,446,434
436,31R445,PORT RICHMOND HIGH SCHOOL,237,437,442,425
437,31R450,CURTIS HIGH SCHOOL,373,439,441,430
438,31R455,TOTTENVILLE HIGH SCHOOL,698,459,482,467
439,31R460,SUSAN E WAGNER HIGH SCHOOL,531,463,482,457
440,31R470,CONCORD HIGH SCHOOL,10,474,431,397
441,31R600,RALPH MCKEE VOC-TECH HIGH SCH,48,411,429,386
442,31R605,STATEN ISLAND TECHNICAL HIGH SCHOOL,287,638,673,617
443,32K403,ACADEMY OF ENVIRONMENTAL LEADERSHIP,36,382,369,374
444,32K480,Bushwick High School,s,s,s,s
445,32K545,EBC High School for Public Service - Bushwick,82,389,390,376
446,32K549,BUSHWICK HS FOR SOCIAL JUSTICE,72,363,364,358
447,32K552,Academy of Urban Planning,49,355,361,353
448,32K554,ALL CITY LEADERSHIP SECONDARY,29,394,420,395
449,32K556,Bushwick Leaders High School for Academic Excel,30,357,345,351
450,72X470,South Bronx High School,s,s,s,s
451,75K371,LILLIAN L RASHKIS HS P371K,s,s,s,s
452,75M035,MANHATTAN HIGH SCHOOL - P35M,s,s,s,s
453,75Q004,P4Q SCHOOL (@ 179),s,s,s,s
454,75Q256,P256 QUEENS SCHOOL @ SAINT MARY'S,s,s,s,s
455,75R025,South Richmond High School,10,407,421,400
456,75X012,PS12X LEWIS AND CLARK SCHOOL,s,s,s,s
457,75X754,P754 X - Jeffrey M. Rapport School for Career ...,s,s,s,s
458,76K460,John Jay High School,9,390,381,398
459,79X490,PHOENIX SCHOOL,7,404,423,416

# What are the top 5 high schools in NYC ranked by SAT scores

In [45]:
sat_data.sort_values('Critical Reading Mean', ascending = False).head(5)

,DBN,School Name,Number of Test Takers,Critical Reading Mean,Mathematics Mean,Writing Mean
394,27Q302,"Queens High School for Information, Research, ...",s,s,s,s
49,02M535,Park West High School,s,s,s,s
93,05M367,Academy for Social Action,s,s,s,s
343,21K412/21K411,YABC AT ABRAHAM LINCOLN HIGH SCHOOL,s,s,s,s
206,11X456,YABC AT HARRY S. TRUMAN HIGH SCHOOL,s,s,s,s

As we can see from above, there are a number of schools that submitted non-numeric data.  Let's turn those 's' strings to NaN nulls, so we can properly run a sort to get our top scores.

In [44]:
good_data = sat_data.replace('s', np.nan)
good_data

,DBN,School Name,Number of Test Takers,Critical Reading Mean,Mathematics Mean,Writing Mean
0,01M292,Henry Street School for International Studies,31,391,425,385
1,01M448,University Neighborhood High School,60,394,419,387
2,01M450,East Side Community High School,69,418,431,402
3,01M458,SATELLITE ACADEMY FORSYTH ST,26,385,370,378
4,01M509,CMSP HIGH SCHOOL,NaN,NaN,NaN,NaN
5,01M515,Lower East Side Preparatory High School,154,314,532,314
6,01M539,"New Explorations into Sci, Tech and Math HS",47,568,583,568
7,01M650,CASCADES HIGH SCHOOL,35,411,401,401
8,01M696,BARD HIGH SCHOOL EARLY COLLEGE,138,630,608,630
9,02M047,AMERICAN SIGN LANG ENG DUAL,11,405,415,385
10,02M288,FOOD AND FNANCE HIGH SCHOOL,50,422,412,407
11,02M294,HIGH SCHOOL FOR HIST AND COMM,51,382,364,366
12,02M296,High School of Hospitality Management,43,397,415,391
13,02M298,PACE HIGH SCHOOL,71,424,448,423
14,02M300,Urban Assembly School of Design and Construction,49,405,446,415
15,02M303,The Facing History School,59,381,373,377
16,02M305,Urban Assembly Academy of Government and Law,48,411,406,411
17,02M308,LOWER MANHATTAN ARTS ACADEMY,35,409,381,412
18,02M313,The James Baldwin School,45,421,419,394
19,02M316,Urban Assembly School of Business for Young Wo...,52,401,409,391
20,02M374,GRAMERCY ARTS HIGH SCHOOL,49,395,376,386
21,02M376,NYC iSchool,NaN,NaN,NaN,NaN
22,02M400,HIGH SCHOOL ENVRNMNTL STUDIES,216,465,480,448
23,02M407,Institute for Collaborative Education,42,484,478,472
24,02M408,Professional Performng Arts School,69,495,465,499
25,02M411,Baruch College Campus High School,96,523,583,528
26,02M412,New York City Laboratory School Collab Studies,108,561,597,567
27,02M413,SCHOOL OF THE FUTURE,79,475,488,466
28,02M414,NEW YORK CITY MUSEUM SCHOOL,90,454,448,435
29,02M416,ELEANOR ROOSEVELT HIGH SCHOOL,122,555,596,567
...,...,...,...,...,...,...
430,30Q555,NEWCOMERS HIGH SCHOOL,147,343,447,346
431,30Q575,ACADEMY OF AMERICAN STUDIES,120,502,505,515
432,30Q580,BACCALAUREATE SCH GLOBAL EDUC,64,560,587,570
433,31R064,Gaynor McCown Expeditionary Learning School,NaN,NaN,NaN,NaN
434,31R080,MICHAEL J PETRIDES SCHOOL,86,508,523,502
435,31R440,NEW DORP HIGH SCHOOL,282,431,446,434
436,31R445,PORT RICHMOND HIGH SCHOOL,237,437,442,425
437,31R450,CURTIS HIGH SCHOOL,373,439,441,430
438,31R455,TOTTENVILLE HIGH SCHOOL,698,459,482,467
439,31R460,SUSAN E WAGNER HIGH SCHOOL,531,463,482,457
440,31R470,CONCORD HIGH SCHOOL,10,474,431,397
441,31R600,RALPH MCKEE VOC-TECH HIGH SCH,48,411,429,386
442,31R605,STATEN ISLAND TECHNICAL HIGH SCHOOL,287,638,673,617
443,32K403,ACADEMY OF ENVIRONMENTAL LEADERSHIP,36,382,369,374
444,32K480,Bushwick High School,NaN,NaN,NaN,NaN
445,32K545,EBC High School for Public Service - Bushwick,82,389,390,376
446,32K549,BUSHWICK HS FOR SOCIAL JUSTICE,72,363,364,358
447,32K552,Academy of Urban Planning,49,355,361,353
448,32K554,ALL CITY LEADERSHIP SECONDARY,29,394,420,395
449,32K556,Bushwick Leaders High School for Academic Excel,30,357,345,351
450,72X470,South Bronx High School,NaN,NaN,NaN,NaN
451,75K371,LILLIAN L RASHKIS HS P371K,NaN,NaN,NaN,NaN
452,75M035,MANHATTAN HIGH SCHOOL - P35M,NaN,NaN,NaN,NaN
453,75Q004,P4Q SCHOOL (@ 179),NaN,NaN,NaN,NaN
454,75Q256,P256 QUEENS SCHOOL @ SAINT MARY'S,NaN,NaN,NaN,NaN
455,75R025,South Richmond High School,10,407,421,400
456,75X012,PS12X LEWIS AND CLARK SCHOOL,NaN,NaN,NaN,NaN
457,75X754,P754 X - Jeffrey M. Rapport School for Career ...,NaN,NaN,NaN,NaN
458,76K460,John Jay High School,9,390,381,398
459,79X490,PHOENIX SCHOOL,7,404,423,416

Once more, let's do the sort and we'll have our top scores.

In [46]:
good_data.sort_values('Critical Reading Mean', ascending = False).head(5)

,DBN,School Name,Number of Test Takers,Critical Reading Mean,Mathematics Mean,Writing Mean
42,02M475,STUYVESANT HIGH SCHOOL,804,674,735,678
442,31R605,STATEN ISLAND TECHNICAL HIGH SCHOOL,287,638,673,617
384,25Q525,Townsend Harris High School at Queens College,273,637,644,642
193,10X696,HS of American Studies at Lehman College,74,635,630,619
185,10X445,BRONX HIGH SCHOOL OF SCIENCE,683,632,685,643

# These were the top 5 schools sorted by their SAT critical reading mean scores.